### ISSUE TITLE
Why Kafka Interceptors are not used for opentracing ?

### ISSUE THREAD

**Issue by kiranpatel11** [opentracing-contrib/java-kafka-client#18]
The implementation provides wrapper using Kafka Producer and Consumer interfaces. 
I think the better way would have been to leverage interceptors to record the span. It has multiple advantages 
1. You dont need to change the places the Producer/Consumer is instantiated.
2. In case of Spring Boot, one can leverage the built-in autoconfigure, yet still provide additional tracing behavior with additional AutoConfiguration, e.g. TracingKafkaAutoConfiguration.

As a reference, please take a look at opentracing support for spring-web https://github.com/opentracing-contrib/java-spring-web/tree/master/opentracing-spring-web

**Comment by malafeev** [comment]
I will add Interceptors implementation as a second option.
Later we can deprecate one of the solution.

**Comment by malafeev** [comment]
added implementation
