### ISSUE TITLE
Use Headers instead of Key to inject Span Context

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/java-kafka-client#2]
Since Kafka 0.11.0.0 will be possible to use headers:
https://issues.apache.org/jira/browse/KAFKA-4208
https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers

**Comment by tedsuo** [comment]
Maybe add a warning at the top of the readme saying that current support is "Experimental" since we are about to change it so drastically.

**Comment by jeqo** [comment]
In case that we will use Headers, there should be one header key for store the `KafkaSpanContext`, right? Any idea of how this key should looks like?

**Comment by malafeev** [comment]
let's wait for official release. 
`tracer.inject(...); tracer.extract(...)` should do the job. I hope to get rid of KafkaSpanContext. Will see.

**Comment by jeqo** [comment]
Ok. 
I give a try with 0.11.0.0-RC1 in https://github.com/opentracing-contrib/java-kafka-client/pull/4:

* Maven repo: https://repository.apache.org/content/groups/staging/org/apache/kafka/
* 0.11.0.0 RC1: http://home.apache.org/~ijuma/kafka-0.11.0.0-rc1/
