### ISSUE TITLE
opentracing-kafka-streams is incompatible with breaking change in Kafka 1.1

### ISSUE THREAD

**Issue by scottadav** [opentracing-contrib/java-kafka-client#20]
With Kafka Streams 1.1, the following exception is thrown upon application startup:

```
java.lang.AbstractMethodError: io.opentracing.contrib.kafka.streams.TracingKafkaClientSupplier.getAdminClient(Ljava/util/Map;)Lorg/apache/kafka/clients/admin/AdminClient;
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:684)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:610)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:590)
        ...
```

This is due to the following breaking change in Kafka 1.1:
https://github.com/apache/kafka/commit/e3c32391f95d82a217295c7e4c1519981124bc3f#diff-3d377b04d0a62ccd4b2bf232422f84adR33

It should be possible to add a default method implementation. If `@Override` is not supplied, then the change should be compatible with both Kafka 1.0 and Kafka 1.1.

**Comment by malafeev** [comment]
merged
