### ISSUE TITLE
How to start Tracing Kafka Produce as child of other span?

### ISSUE THREAD

**Issue by krishg443** [opentracing-contrib/java-kafka-client#22]
How to start Tracing Kafka Produce as child of other span?

I would like to see Kafka transaction under single request.
Example: 
I have 1. Rest based service. Its normally initiate GlobalTracer and Span and Start.
It has to send kafka event and receive event.

I want to see this one in single transaction.

Please suggest.

**Comment by malafeev** [comment]
you need to have active scope in the thread where producer send message.
If you are using instrumentation for REST like [OpenTracing Spring Web instrumentation](https://github.com/opentracing-contrib/java-spring-web) then in controller you will have activated scope.
