### ISSUE TITLE
Tracing other components when consuming records

### ISSUE THREAD

**Issue by emersonborges** [opentracing-contrib/java-kafka-client#23]
Let's suppose i have a consumer that does a lot of processing, makes request calls with feign, saves on database, etc... how do i trace all these operations under same traceId?

**Comment by malafeev** [comment]
You need to retrieve SpanContext from polled record.
```
ConsumerRecord<Integer, String> record = ...
SpanContext spanContext = TracingKafkaUtils.extractSpanContext(record.headers(), tracer);
```
Then create new span with parent `spanContext`:
```
try(Scope scope = tracer.buildSpan("consume").asChildOf(spanContext).startActive(true)) {
    // make here feign, database and any other calls. 
}
```

**Comment by emersonborges** [comment]
Nice! Thank you for the answer!
