### ISSUE TITLE
Use a language-neutral serialization format

### ISSUE THREAD

**Issue by nightscape** [opentracing-contrib/java-kafka-client#3]
As far as I understand [the code here](https://github.com/opentracing-contrib/java-kafka-client/blob/master/src/main/java/io/opentracing/contrib/kafka/KafkaSpanContextSerializer.java#L28), `java-kafka-client` is using Java serialization to send trace information across the wire.
This makes it impossible to use in a multi-language setting.
Would it be possible / is it planned to use a language-neutral serialization format like JSON, Avro, Thrift. Protobuf?

**Comment by malafeev** [comment]
you are right, but I hope #2 will fix it much better way

**Comment by nightscape** [comment]
Definitely! But that will only work for Kafka 0.11, right?
Do you know by any chance what the ETA of 0.11 is?

**Comment by malafeev** [comment]
Yes, that will work only for 0.11
Release: June 14, 2017
