### ISSUE TITLE
Why does TracingCallback take a Scope?

### ISSUE THREAD

**Issue by yurishkuro** [opentracing-contrib/java-kafka-client#31]
Presumably, the point of a "callback" is that it can be executed in another thread, so passing it a Scope, which should only be accessed from one thread, seems like a mistake. Instead, it should only be passed the Span and finish it when done.

https://github.com/opentracing-contrib/java-kafka-client/blob/77346c629335f752a7c5c6dc1771d437d0092e89/opentracing-kafka-client/src/main/java/io/opentracing/contrib/kafka/TracingCallback.java#L29

**Comment by malafeev** [comment]
fixed
