### ISSUE TITLE
Incompatible with Kafka 2.0.0

### ISSUE THREAD

**Issue by davispw** [opentracing-contrib/java-kafka-client#33]
KIP-266, released in Kafka 2.0.0, added a [new method](https://cwiki.apache.org/confluence/display/KAFKA/KIP-266%3A+Fix+consumer+indefinite+blocking+behavior#KIP-266:Fixconsumerindefiniteblockingbehavior-Consumer#poll) to the KafkaConsumer API.

This is causing 
```
java.lang.AbstractMethodError: io.opentracing.contrib.kafka.TracingKafkaConsumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
```

**Comment by malafeev** [comment]
fixed, will be available in 0.0.15 release within 24 hours
