### ISSUE TITLE
[Opentracing Kafka with springboot] java.lang.AbstractMethodError: io.jaegertracing.internal.JaegerTracer.activateSpan(Lio/opentracing/Span;)Lio/opentracing/Scope;

### ISSUE THREAD

**Issue by gabin0801** [opentracing-contrib/java-kafka-client#45]
Hello. everyone.

When trying to apply kafka with opentracing in springboot, I'm always meeting under error.

**java.lang.AbstractMethodError: io.jaegertracing.internal.JaegerTracer.activateSpan(Lio/opentracing/Span;)Lio/opentracing/Scope;
	at io.opentracing.contrib.kafka.TracingKafkaProducer.send(TracingKafkaProducer.java:117) ~[opentracing-kafka-client-0.1.1.jar:na]**

in my build.gradle, I'm using 4 opntracing contrib dependencies.
`

	compile group: 'io.opentracing.contrib', name: 'opentracing-spring-jaeger-cloud-starter', version: '1.0.3'
	compile group: 'io.opentracing.contrib', name: 'opentracing-spring-zipkin-cloud-starter', version: '0.2.0'
	compile group: 'io.opentracing.contrib', name: 'opentracing-spring-cloud-starter', version: '0.2.4'

	// https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-spring-web-autoconfigure
	// compile group: 'io.opentracing.contrib', name: 'opentracing-spring-web-autoconfigure', version: '0.3.2'

	// https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-kafka-spring
	compile group: 'io.opentracing.contrib', name: 'opentracing-kafka-spring', version: '0.1.1'

`

and, in my application.properies,

**server.port=8081
spring.application.name=opentracing-spring-ex-1

opentracing.jaeger.enabled=true
opentracing.jaeger.service-name=op-spring-jaeger-ex-1
opentracing.jaeger.http-sender.url=localhost:14268/api/traces
opentracing.jaeger.const-sampler.decision=true
opentracing.jaeger.probabilistic-sampler.sampling-rate=1.0
opentracing.jaeger.rate-limiting-sampler.max-traces-per-second=1.0
#for compatibility with Zipkin collectors
opentracing.jaeger.enable-b3-propagation = true** 

in my configuration, I just register kafka producer and template. 
because as you know, tracer already registered in spring bean(JaegerAutoConfiguration).

`
@ConditionalOnClass(JaegerAutoConfiguration.class)
@Configuration
public class PtKafkaConfiguration
{
    @Autowired
    io.opentracing.Tracer tracer;

    // Decorate ProducerFactory with TracingProducerFactory
    @Bean
    public ProducerFactory<Integer, String> producerFactory()
    {
        return new TracingProducerFactory<>(new DefaultKafkaProducerFactory<>(producerProps()), tracer);
    }

    // Use decorated ProducerFactory in KafkaTemplate
    @Bean
    public KafkaTemplate<Integer, String> kafkaTemplate()
    {
        return new KafkaTemplate<>(producerFactory());
    }

    private Map<String, Object> producerProps()
    {
        Map<String, Object> config = new HashMap<>();

        config.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        config.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, LongSerializer.class);
        config.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);

        return config;
    }
}
`

and, in my controller, I call kafkaTemplate.send and always met error related to 
**java.lang.AbstractMethodError: io.jaegertracing.internal.JaegerTracer.activateSpan(Lio/opentracing/Span;)Lio/opentracing/Scope;**

`

@Slf4j
@RestController
public class Ex1Controller
{
    @Autowired
    private io.opentracing.Tracer tracer;
    
    @Autowired
    private KafkaTemplate<Integer, String> kafkaTemplate;

    @GetMapping("/sayHello/{name}")
    public String sayHello(@PathVariable String name)
    {
        // this.kafkaTemplate.send("greetings-topic", "CHA!");
        log.info("sayHello ENTER >>>");

        io.opentracing.Span span = this.tracer.buildSpan("sayHello-span").start();

        //try (io.opentracing.Scope scope = this.tracer.scopeManager().activate(span, false)) {
        try (io.opentracing.Scope scope = this.tracer.scopeManager().activate(span)) {
            
            // log send using string
            span.log("my string data");
            // log tag
            span.setTag("tag key1", "tag value 1");
            span.setTag("tag key2", "tag value 2");
            span.setTag("tag key3", "value key 3");

            String response = this.requestFormatGreeting(name);
            span.setTag("response", response);

            return response;
        } finally {
            span.finish(); // you must finish your span.
        }
    }
    
    private String requestFormatGreeting(String str)
    {
        log.info("requestFormatGreeting ENTER >>>");
        ListenableFuture<SendResult<Integer, String>> result = kafkaTemplate.send("greetings-topic", "SSSSSSSSSS");
        result.addCallback(success -> {
            log.info(success.toString());
        }, exception -> {
            log.info(exception.getMessage());
        });
        return "Hello, " + str;
    }
}

`

When checking test codes, I cannot find any difference in my codes. :(
Can you guide me about this problem?

**Comment by malafeev** [comment]
@gabin0801 Jaeger tracer you are using doesn't support latest opentracing api 0.32.0
I suggest you use old version of `java-kafka-client` (0.0.20) or wait jaeger: https://github.com/jaegertracing/jaeger-client-java/issues/614
