### ISSUE TITLE
Spans created by Consumer not picked up by Producer

### ISSUE THREAD

**Issue by thall** [opentracing-contrib/java-kafka-client#49]
I'm using opentracing-kafka-streams and want to start a trace when a message is consumed in `cs_asn_decoder` which produces to `zc_pmm_service` which produces to `zc_ppt_populator` in an linear fashion.

I'm expecting this to work out of the box but it seems that consumer creates a span and store it in the headers as `second_span_*` (https://github.com/opentracing-contrib/java-kafka-client/blob/master/opentracing-kafka-client/src/main/java/io/opentracing/contrib/kafka/TracingKafkaUtils.java#L136 ) but i cant find any trying to pick up that header. No one is calling (https://github.com/opentracing-contrib/java-kafka-client/blob/master/opentracing-kafka-client/src/main/java/io/opentracing/contrib/kafka/TracingKafkaUtils.java#L52).

This results in an unexpected trace (but there is maybe an explanation for this?).
![jaeger-broken-timeline](https://user-images.githubusercontent.com/102452/58556193-a83feb80-821b-11e9-8c7e-ecf61d9980bc.png)
![jaeger-broken-graph](https://user-images.githubusercontent.com/102452/58556202-ac6c0900-821b-11e9-988e-4da0554125ec.png)
From the graph above we can see that the span start from `cs-asn-decoer: To_thall.zc.device..`, hence not from the consumer as I expected. 
We also see that `zc-pmm-service: To_thall.zc.device..` are children (solid line) which i don't expect either, they should be children of `zc-pmm-service: From_thall.zc.device...`. 

I published a draft of how I thought it should work were I inject the span without the `second_span_*` prefix, see https://github.com/thall/java-kafka-client/commit/eb50d9e1d6908352940081c7fa032e8baaea76f1 .

I then run the same scenario as above with this outcome:
![jaeger-timeline](https://user-images.githubusercontent.com/102452/58556773-1802a600-821d-11e9-9dd3-4fb1680310c7.png)
![jaeger-graph](https://user-images.githubusercontent.com/102452/58556783-1df88700-821d-11e9-843e-1c6fd37fb9c9.png)

Here we can see we have a linear trace starting from the consumer where the produce-trace are children of the previous consumed messages.

Is this expected behavior or have i missed something how i could correlate as above with out my changes? (I know I can access the headers in a transformer and fix it there but it feels like a hack)

**Comment by malafeev** [comment]
thanks @thall 
the question is why we inject consumer span context with `second_span_` prefix to consumer record headers?
Consumer headers usually already contains span context from producer.
But is it safe to override span context? Can we corrupt context data to be invalid for extraction? Because I'm not sure about answer I added `second_span_` prefix.
It would be great to remove initial context data from headers, but I there is no way to do it.

**Comment by malafeev** [comment]
We can add boolean flag to `TracingKafkaClientSupplier` constructor to indicate that we want inject consumer span context without `second_span_` prefix. Although I'm still not sure is it good or not.

**Comment by thall** [comment]
> the question is why we inject consumer span context with second_span_ prefix to consumer record headers?

Yes, i don't understand why you do it? No one every reads it any way?

>  Consumer headers usually already contains span context from producer.

Yes, usually, but if it does we still have the same problem. ( See first graph, yellow and brown)

> But is it safe to override span context? Can we corrupt context data to be invalid for extraction?

I can't really see this happens, I assume you use the library in all your services.

> We can add boolean flag to TracingKafkaClientSupplier constructor to indicate that we want inject consumer span context without second_span_ prefix. Although I'm still not sure is it good or not.

That would be one quick solution, but I think we should think through how it should be used.

How about:

- If you look at my first graph (not the timeline), how would you interpreter it? Do you think its correct? 
- Is my use-case valid? Wouldn't you prefer the last graph in that case?

**Comment by thall** [comment]
> Different tracers can implement it different way. We use API level.
If it works with Jaeger - great. Will it work with other tracers?

We are using Opentracing `tracer` were `jeager` is an implementation of that API, so other tracers that implement the same API should work?

> Your use case is specific to streams. In regular kafka app you can extract consumer span using utility method. That's why I propose quick fix for streams.

I don't think it is specific to streams. Streams is just an abstraction on top of Producer / Consumer, as you can see here https://github.com/opentracing-contrib/java-kafka-client/blob/master/opentracing-kafka-streams/src/main/java/io/opentracing/contrib/kafka/streams/TracingKafkaClientSupplier.java#L90 . Its possible to extract the headers in an `Transformer`.

**Comment by malafeev** [comment]
fixed in #50

**Comment by thall** [comment]
Thanks @malafeev :thumbsup:
