### ISSUE TITLE
About relationship between producer span and consumer span

### ISSUE THREAD

**Issue by hotdust** [opentracing-contrib/java-kafka-client#54]
I try to make a tracer of rocketmq, and have a question about relationship between producer span and consumer span. 

Question:
The relationship between producer span and consumer span is addReference, but not asChildOf. It's very appreciated that if talk about thinking that choose addReference other than asChildOf.

Personal point:
Consumers look like other service interface, so asChildOf replationship maybe better.

**Comment by malafeev** [comment]
it's as specification: https://github.com/opentracing/specification/blob/master/semantic_conventions.md#message-bus

**Comment by hotdust** [comment]
sorry for not reading specification carefullly.
