### ISSUE TITLE
Is there any solution for kafka version without header

### ISSUE THREAD

**Issue by caorui31** [opentracing-contrib/java-kafka-client#56]
Hi guys，

In my project， I use kafka with version 0.10
So, Is there any solution for this, I need to carry trace information when passing data by kafka.

**Comment by malafeev** [comment]
Kafka versions before 1.0.0 doesn't support headers therefore passing span context from producer to consumer is complicated.
I tried to fix it in old versions of this lib e.g. 0.0.3
You can try to use it, but it was too tricky to implement.

**Comment by caorui31** [comment]
> Kafka versions before 1.0.0 doesn't support headers therefore passing span context from producer to consumer is complicated.
> I tried to fix it in old versions of this lib e.g. 0.0.3
> You can try to use it, but it was too tricky to implement.
> And OpenTracing API those days was different...

thanks.  I will have a try, because of in my project . kafka version only support below 0.11
