### ISSUE TITLE
Java.lang.NosuchaMethoderror:Io.opentracing.scoprmanager.active()/Lio/ooentracing/scope

### ISSUE THREAD

**Issue by ADDale** [opentracing-contrib/java-kafka-client#58]
Hello Team,
I am trying simple program to Kafka producer interceptor.

However I am getting error as per attached screenshot.

Can someone please help. Maybe issue with the versions I am using? I have also attached the gradle file.

Added the missing screenshots.

Regards,
Amruta

**Comment by ADDale** [comment]
![IMG_20191014_145608](https://user-images.githubusercontent.com/46351937/66741596-81fdae00-ee93-11e9-827e-a5dac0e2e328.jpg)
![IMG_20191014_145558](https://user-images.githubusercontent.com/46351937/66741627-90e46080-ee93-11e9-95e4-ffdb5b4a86d8.jpg)

**Comment by malafeev** [comment]
yes, the problem in the dependency versions.
all `io.opentracing` dependencies should be version 0.33.0
`jaeger-core` version 1.0.0
