### ISSUE TITLE
TracingProducerFactory is not compatible with spring-kafka:2.3.1

### ISSUE THREAD

**Issue by ZawadaZSE** [opentracing-contrib/java-kafka-client#60]
Hey,

SpringKafka added new method to ProducerFactory interface with this change: https://github.com/spring-projects/spring-kafka/pull/1105
which makes opentracing-kafka-spring incompatible with SpringKafka 2.3.0+

Because of that TracingProducerFactory does not work (UnsupportedOperationException("This factory does not support this method") is thrown)

SpringKafka 2.3.1 is default for SpringBoot 2.2.0

**Comment by malafeev** [comment]
fixed via #61

**Comment by ZawadaZSE** [comment]
That was fast ;) Thanks!
