### ISSUE TITLE
jackson-databind vulnerabilities using kafka_2.12 version 2.3.0

### ISSUE THREAD

**Issue by jondey** [opentracing-contrib/java-kafka-client#63]
Hi

Version 2.3.0 of org.apache.kakfa:kafka_2.12 has jackson-databind vulnerabilities.
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-455617

Jackson libraries have been upgraded in 2.3.1.

Can kafka.version property in the parent pom be updated to 2.3.1?

```
<kafka.version>2.3.1</kafka.version>
```

**Comment by malafeev** [comment]
fixed via #64
