### ISSUE TITLE
SNYK issue -> org.lz4:lz4-java:1.6.0:jar

### ISSUE THREAD

**Issue by jondey** [opentracing-contrib/java-kafka-client#65]
Still appears to be an issue with the above library:
https://snyk.io/vuln/SNYK-JAVA-ORGLZ4-473117

Fix has been merged but not released yet -> https://github.com/lz4/lz4-java/issues/150

**Comment by malafeev** [comment]
I suppose issue should be submitted to ` org.apache.kafka:kafka-clients`

**Comment by jondey** [comment]
Yes - I'll do that.
