### ISSUE TITLE
Inconsistent topic tag name in producer and consumer span decorators

### ISSUE THREAD

**Issue by zserge** [opentracing-contrib/java-kafka-client#70]
Decorating producer span seems to set `message_bus.destination` tag, which matches opentracing spec (https://github.com/opentracing/specification/blob/master/semantic_conventions.md).

However, decorating consumer spans sets `topic` tag, which is not mentioned in opentracing docs. As a result, certain tracer implementations do not detect such consumer spans as a "Messaging" type of a span. Is there any reason behind such a choice of the tag names?

**Comment by malafeev** [comment]
no, seems a bug

**Comment by zserge** [comment]
@malafeev Would you like me to make a PR to speed things up?

**Comment by malafeev** [comment]
Sure @zserge

**Comment by malafeev** [comment]
fixed via #71
