### ISSUE TITLE
Do we have an option to add custom tags

### ISSUE THREAD

**Issue by nichuHere** [opentracing-contrib/java-kafka-client#73]
This is more a question than and issue.
Can we add custom tags?
I would like to capture the key of a kafka message as a custom tag to identify the record that is being captured in a trace.

**Comment by malafeev** [comment]
@nichuHere yes, that's possible, please look at [SpanDecorator](https://github.com/opentracing-contrib/java-kafka-client/blob/master/opentracing-kafka-client/src/main/java/io/opentracing/contrib/kafka/SpanDecorator.java) interface, you can provide own implementation.

**Comment by nichuHere** [comment]
@malafeev I did try that.. but the TracingKafkaProducer constructor that accepts spanDecorators is not public.
Hence cant instantiate it.

`    val spanDecorators: MutableCollection<SpanDecorator> = ArrayList<SpanDecorator>()
        spanDecorators.add(CustomSpanDecorator())

        val producerSpanNameProvider =
            BiFunction { operationName: String, producerRecord: ProducerRecord<*, *> -> "CUSTOM_PRODUCER_NAME" }
        val tracingProducer: TracingKafkaProducer<String, TaxServicingEvent> =
            TracingKafkaProducer(producer, tracer,spanDecorators,producerSpanNameProvider)`

**Comment by malafeev** [comment]
@nichuHere you have to use `TracingKafkaProducerBuilder`

**Comment by nichuHere** [comment]
Thankyou just figured that ... :)
