### ISSUE TITLE
Custom Tag not visible in ConsumerApp

### ISSUE THREAD

**Issue by nichuHere** [opentracing-contrib/java-kafka-client#76]
Producer1 publishes messages with custom tag to Topic1
Consumer1 retrieves the message, performs transformation, publishes the message to Topic 2 

Custom tag is visible in Producer1 span
Custom tag not visible in Consumer1 span
Custom tag visible in Producer of Consumer1.

What am I missing?

**Comment by malafeev** [comment]
@nichuHere tags are not passed from span to span.
