### ISSUE TITLE
Expose `TracingKafkaUtils` as public to inject `spanContext` from another `span`

### ISSUE THREAD

**Issue by jeqo** [opentracing-contrib/java-kafka-client#8]
I'd need to reference an existing `span` from `TracingKafkaProducer` to continue a `trace`.

Is there any other way to inject an `spanContext` (e.g. from Dropwizard) into headers to be linked on `TracingKafkaProducer`?

**Comment by malafeev** [comment]
Solution is to build chain of spans (parent-child):
You need to activate span before producer `send` record.
E.g. 
```
try(ActiveSpan activeSpan = tracer.makeActive(span)) {
producer send(producerRecord);
}
```
But before you need build span from `spanContext` (I assume you have only `spanContext`):

```
try(tracer.buildSpan("dropwizard").asChildOf(spanContext).startActive()) {
   producer send(producerRecord);
}
```

**Comment by jeqo** [comment]
thanks @malafeev ! It is working fine on the Producer side, but how to make reference to the `span` created by the consumer once it poll messages?

**Comment by malafeev** [comment]
I will add public `extractSpanContext` method to `TracingKafkaUtils`: 
```
 public static SpanContext extractSpanContext(Headers headers, Tracer tracer) {
    ...
  }
```
