### ISSUE TITLE
Release public support for SpanDecorators

### ISSUE THREAD

**Issue by william-tran** [opentracing-contrib/java-kafka-client#82]
Can we get a release for https://github.com/opentracing-contrib/java-kafka-client/pull/78 please? I'd like to add my own span decorator that makes better use of the `To` span duration, so that we can express the produce-> consume lag as the consumer span's duration

**Comment by malafeev** [comment]
version 0.1.14 released

**Comment by william-tran** [comment]
thanks for the quick turnaround!
