### ISSUE TITLE
Version 0.1.15 is not installable from Bintray JCenter

### ISSUE THREAD

**Issue by denisw** [opentracing-contrib/java-kafka-client#85]
I saw that version 0.1.15 of `opentracing-kafka-client` was pushed to JCenter after the merge of #84. However, I cannot install it from there or Maven Central:

* On JCenter there is only `opentracing-kafka-client`, but not `opentracing-kafka-spring` or `opentracing-kafka-streams`, both of which I need as well

* On Maven Central, all three artifacts are still at version 0.1.14

**Comment by malafeev** [comment]
should be available now in Maven Central
https://repo1.maven.org/maven2/io/opentracing/contrib/opentracing-kafka-spring/0.1.15/

**Comment by denisw** [comment]
Works now, thanks!
